"""Extended state definitions for JEE calculus problem-solving agent.

The ``JEEAgentState`` TypedDict extends the base ``AgentState`` with
fields specific to symbolic calculus: problem-type classification, step-by-step
solution plans, SymPy code/results, symbolic step traces, LaTeX answers, and
confidence scores.

Usage::

    from agent.jee_state import JEEAgentState

    state: JEEAgentState = {
        "problem": "lim x->0 sin(x)/x",
        "problem_type": "limits",
        ...
    }
"""

from typing import TypedDict, Annotated, Optional
import operator


class JEEAgentState(TypedDict):
    """Typed dictionary representing the JEE agent's state throughout execution.

    Fields
    ------
    problem : str
        The raw JEE problem statement.
    problem_type : Optional[str]
        Classification of the problem: ``"limits"``, ``"differentiation"``,
        ``"integration"``, ``"definite_integrals"``, ``"differential_equations"``,
        ``"maxima_minima"``, ``"tangent_normal"``, ``"area"``,
        ``"continuity"``, ``"series"``, or ``"other"``.
    key_concepts : list[str]
        Mathematical concepts and theorems identified as relevant (populated
        during the *analyse* node).
    solution_plan : Optional[str]
        JSON-serialised step-by-step plan generated by the *plan* node.
    thought : str
        Current reasoning / working thought (used by LLM nodes).
    code : Optional[str]
        Generic Python code produced by the agent (legacy / numeric path).
    sympy_code : Optional[str]
        SymPy Python code generated for the current symbolic step.
    sympy_result : Optional[str]
        String output returned by executing ``sympy_code``.
    code_result : Optional[str]
        Result of executing generic *code* (legacy field).
    answer : Optional[str]
        Intermediate answer string (legacy field).
    steps : Annotated[list[dict], operator.add]
        Accumulated solution steps, each a dict with keys ``description``,
        ``tool``, ``code``, ``result``, etc.
    symbolic_steps : list[str]
        Flat list of SymPy commands executed across all steps (audit trail).
    reasoning_trace : Annotated[list[str], operator.add]
        Append-only list of human-readable reasoning strings.
    verification : Optional[str]
        JSON-serialised verification report from the *verify* node.
    reflection : Optional[str]
        JSON-serialised reflection when verification fails.
    retry_count : int
        Number of reflection→replan cycles attempted.
    final_answer : Optional[str]
        Plain-text final answer.
    latex_answer : Optional[str]
        LaTeX-formatted final answer.
    confidence : float
        Confidence score in ``[0, 1]`` (populated by the *verify* node).
    done : bool
        Flag indicating whether the graph has reached an end state.
    """

    # -- Core problem fields ------------------------------------------------
    problem: str
    problem_type: Optional[str]
    key_concepts: list[str]
    solution_plan: Optional[str]

    # -- Current working state ----------------------------------------------
    thought: str
    code: Optional[str]
    sympy_code: Optional[str]
    sympy_result: Optional[str]
    code_result: Optional[str]
    answer: Optional[str]

    # -- Accumulated steps --------------------------------------------------
    steps: Annotated[list[dict], operator.add]
    symbolic_steps: list[str]
    reasoning_trace: Annotated[list[str], operator.add]

    # -- Verification / reflection ------------------------------------------
    verification: Optional[str]
    reflection: Optional[str]
    retry_count: int

    # -- Final output -------------------------------------------------------
    final_answer: Optional[str]
    latex_answer: Optional[str]
    confidence: float
    done: bool
