"""Node functions for the LangGraph math reasoning agent."""

import json
import re
from typing import Optional

from langchain_core.messages import HumanMessage, SystemMessage

from agent.state import AgentState
from agent.prompts import (
    EXTRACT_PROMPT,
    REFLECT_PROMPT,
    SYSTEM_PROMPT,
    THINK_PROMPT,
    VERIFY_PROMPT,
)
from agent.tools import PythonREPLTool


def parse_json_response(response_text: str) -> dict:
    """Parse a JSON response from the LLM, handling markdown fences and common errors.

    Args:
        response_text: Raw text response from the LLM.

    Returns:
        Parsed dictionary or empty dict on failure.
    """
    if not response_text:
        return {}

    text = response_text.strip()

    # Strip markdown code fences
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"```\s*$", "", text)
    text = text.strip()

    # Try direct parse
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try regex: find the first '{' and last '}'
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass

    # Try line-by-line: find first line starting with '{' and last line ending with '}'
    lines = text.splitlines()
    start_idx = None
    end_idx = None
    for i, line in enumerate(lines):
        if start_idx is None and "{" in line:
            start_idx = i
        if "}" in line:
            end_idx = i
    if start_idx is not None and end_idx is not None and end_idx >= start_idx:
        json_block = "\n".join(lines[start_idx : end_idx + 1])
        try:
            return json.loads(json_block)
        except json.JSONDecodeError:
            pass

    # Try fixing common LLM JSON issues: trailing commas
    fixed = re.sub(r",(\s*[}\]])", r"\1", text)
    try:
        return json.loads(fixed)
    except json.JSONDecodeError:
        pass

    # Last resort: try to extract key-value pairs manually
    try:
        result: dict = {}
        # Match "key": "value" or "key": number or "key": bool/null patterns
        pattern = r'"(\w+)":\s*("(?:[^"\\]|\\.)*"|\[[\s\S]*?\]|\{[\s\S]*?\}|true|false|null|\d+(?:\.\d+)?)'
        for m in re.finditer(pattern, text):
            key = m.group(1)
            val_str = m.group(2).strip()
            try:
                result[key] = json.loads(val_str)
            except json.JSONDecodeError:
                result[key] = val_str.strip('"')
        return result
    except Exception:
        return {}


def think_node(state: AgentState, llm, config) -> dict:
    """Generate initial reasoning and code for the problem.

    Args:
        state: Current agent state.
        llm: LangChain chat model.
        config: Application configuration.

    Returns:
        Dictionary with thought, code, reasoning_trace, and retry_count.
    """
    problem = state.get("problem", "")
    if not problem:
        return {
            "thought": "Error: No problem provided.",
            "code": "print(0)",
            "reasoning_trace": ["Error: No problem provided."],
            "retry_count": 0,
        }

    prompt = THINK_PROMPT.format(problem=problem)
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    try:
        response = llm.invoke(messages)
        parsed = parse_json_response(response.content)
    except Exception as exc:
        return {
            "thought": f"Error during think step: {exc}",
            "code": "print(0)",
            "reasoning_trace": [f"Think error: {exc}"],
            "retry_count": 0,
        }

    thought = str(parsed.get("thought", "")) if parsed else ""
    code = str(parsed.get("code", "")) if parsed else ""

    if not code:
        code = "print(0)"

    reasoning_entry = f"THINK: {thought}\nCODE:\n{code}"

    return {
        "thought": thought,
        "code": code,
        "reasoning_trace": [reasoning_entry],
        "retry_count": 0,
    }


def execute_node(state: AgentState, config) -> dict:
    """Execute the Python code generated by the think node.

    Args:
        state: Current agent state.
        config: Application configuration.

    Returns:
        Dictionary with code_result.
    """
    code = state.get("code", "")
    if not code:
        return {"code_result": "Error: No code to execute."}

    repl = PythonREPLTool(timeout=5)
    try:
        result = repl.run(code)
    except Exception as exc:
        result = f"Error: Execution failed: {exc}"

    return {"code_result": result}


def verify_node(state: AgentState, llm, config) -> dict:
    """Verify the correctness of the solution.

    Args:
        state: Current agent state.
        llm: LangChain chat model.
        config: Application configuration.

    Returns:
        Dictionary with verification result and done flag.
    """
    problem = state.get("problem", "")
    thought = state.get("thought", "")
    code = state.get("code", "")
    code_result = state.get("code_result", "")

    prompt = VERIFY_PROMPT.format(
        problem=problem,
        thought=thought,
        code=code,
        code_result=code_result,
    )
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    try:
        response = llm.invoke(messages)
        parsed = parse_json_response(response.content)
    except Exception as exc:
        return {
            "verification": f"Verification error: {exc}",
            "done": False,
        }

    if not parsed:
        return {
            "verification": "Failed to parse verification response.",
            "done": False,
        }

    is_correct = bool(parsed.get("is_correct", False))
    confidence = float(parsed.get("confidence", 0.0)) if "confidence" in parsed else 0.0
    issues = parsed.get("issues", [])
    if isinstance(issues, str):
        issues = [issues]
    elif not isinstance(issues, list):
        issues = []

    verification_text = (
        f"Correct: {is_correct}, Confidence: {confidence}, Issues: {issues}"
    )

    return {
        "verification": verification_text,
        "done": is_correct,
    }


def reflect_node(state: AgentState, llm, config) -> dict:
    """Reflect on verification failures and produce corrected code.

    Args:
        state: Current agent state.
        llm: LangChain chat model.
        config: Application configuration.

    Returns:
        Dictionary with reflection, corrected code, and incremented retry_count.
    """
    retry_count = state.get("retry_count", 0)
    max_retries = getattr(config, "MAX_RETRIES", 3)

    if retry_count >= max_retries:
        return {
            "reflection": f"Max retries ({max_retries}) reached. Proceeding with best effort.",
            "done": True,
        }

    problem = state.get("problem", "")
    thought = state.get("thought", "")
    code = state.get("code", "")
    verification = state.get("verification", "")

    # Extract issues from verification text
    issues = verification
    if "Issues:" in verification:
        parts = verification.split("Issues:", 1)
        if len(parts) > 1:
            issues = parts[1].strip()

    prompt = REFLECT_PROMPT.format(
        problem=problem,
        thought=thought,
        code=code,
        issues=issues,
    )
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    try:
        response = llm.invoke(messages)
        parsed = parse_json_response(response.content)
    except Exception as exc:
        return {
            "reflection": f"Reflection error: {exc}",
            "retry_count": retry_count + 1,
        }

    if not parsed:
        return {
            "reflection": "Failed to parse reflection response.",
            "retry_count": retry_count + 1,
        }

    reflection = str(parsed.get("reflection", ""))
    corrected_code = str(parsed.get("corrected_code", ""))

    if not corrected_code:
        corrected_code = code

    reasoning_entry = f"REFLECT (attempt {retry_count + 1}): {reflection}\nCORRECTED CODE:\n{corrected_code}"

    return {
        "reflection": reflection,
        "code": corrected_code,
        "reasoning_trace": [reasoning_entry],
        "retry_count": retry_count + 1,
    }


def format_node(state: AgentState, llm, config) -> dict:
    """Extract the final numerical answer from the code execution result.

    Args:
        state: Current agent state.
        llm: LangChain chat model.
        config: Application configuration.

    Returns:
        Dictionary with final_answer and done=True.
    """
    code_result = state.get("code_result", "")
    problem = state.get("problem", "")

    if not code_result:
        return {"final_answer": "0", "done": True}

    # First, try LLM-based extraction
    prompt = EXTRACT_PROMPT.format(text=code_result, problem=problem)
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=prompt),
    ]

    llm_answer: Optional[str] = None
    try:
        response = llm.invoke(messages)
        parsed = parse_json_response(response.content)
        if parsed and "answer" in parsed:
            llm_answer = str(parsed["answer"]).strip()
    except Exception:
        pass

    if llm_answer:
        return {"final_answer": llm_answer, "done": True}

    # Fallback: regex extraction
    final_answer = _extract_answer_fallback(code_result)
    return {"final_answer": final_answer, "done": True}


def _extract_answer_fallback(text: str) -> str:
    """Extract the final numerical answer using regex heuristics.

    Handles integers, decimals, and fractions.

    Args:
        text: The code execution result text.

    Returns:
        Clean numerical answer string.
    """
    if not text:
        return "0"

    # Remove error prefix
    if text.startswith("Error:"):
        return "0"

    # Handle fractions like "3/4"
    frac_match = re.search(r"(\d+)\s*/\s*(\d+)", text)
    if frac_match:
        try:
            numerator = int(frac_match.group(1))
            denominator = int(frac_match.group(2))
            if denominator != 0:
                return str(numerator / denominator)
        except (ValueError, ZeroDivisionError):
            pass

    # Find all numbers (integers, decimals, negative numbers)
    numbers = re.findall(r"-?\d+\.?\d*", text)
    if numbers:
        # Filter out obvious non-answers (like "1." at end of sentences)
        filtered = [n for n in numbers if len(n.replace(".", "").replace("-", "")) > 0]
        if filtered:
            # Return the last number (most likely the final answer)
            return filtered[-1]

    return "0"
